In [1]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

In [10]:
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)

In [7]:
demo_data = pd.read_csv("C:\\Users\\realn\\PycharmProjects\\MFDP\\app\\artifacts\\07_best_demo_data.csv")

In [15]:
demo_data

,bureau_AMT_CREDIT_SUM_min,prev_SELLERPLACE_AREA_min,AMT_INCOME_TOTAL,prev_AMT_DOWN_PAYMENT_mean,prev_WEEKDAY_APPR_PROCESS_START_SATURDAY_count_norm,bureau_AMT_CREDIT_SUM_DEBT_max,bureau_DAYS_CREDIT_UPDATE_mean,bureau_DAYS_CREDIT_UPDATE_max,prev_NAME_GOODS_CATEGORY_Furniture_count_norm,bureau_DAYS_ENDDATE_FACT_max,AMT_REQ_CREDIT_BUREAU_QRT,OWN_CAR_AGE,bureau_DAYS_CREDIT_ENDDATE_max,prev_CNT_PAYMENT_mean,BASEMENTAREA_AVG,LANDAREA_AVG,bureau_AMT_CREDIT_SUM_DEBT_min,FLAG_OWN_CAR,ORGANIZATION_TYPE_Self-employed,FLOORSMIN_AVG,FLOORSMAX_AVG,DAYS_BIRTH,NONLIVINGAREA_AVG,APARTMENTS_AVG,HOUSETYPE_MODE_block of flats,EXT_SOURCE_2,NONLIVINGAPARTMENTS_AVG,YEARS_BUILD_AVG,COMMONAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,EXT_SOURCE_1,EXT_SOURCE_3
0,0.000,4.0,261000.0,0.00,0.000000,638496.000,-250.666667,-15.0,0.0,-813.0,0.000000,8.000000,1043.0,36.0,0.092500,0.127900,0.0,1,0,0.208300,0.166700,-16499,0.017000,0.158800,1,0.552325,0.000000,0.755200,0.019100,0.982100,0.560240,0.429424
1,40275.000,550.0,180000.0,17858.25,0.000000,0.000,-1366.333333,-237.0,0.0,-307.0,0.000000,10.685750,-300.0,8.0,0.080988,0.046918,0.0,0,0,0.205958,0.166579,-15828,0.002104,0.094190,0,0.665421,0.001141,0.767218,0.025254,0.981863,0.599098,0.843544
2,1350000.000,-1.0,157500.0,0.00,0.000000,2134080.495,-195.333333,-36.0,0.0,-245.0,0.000000,14.255488,2302.0,60.0,0.080367,0.047711,0.0,0,1,0.206577,0.167830,-17258,0.005465,0.093094,0,0.184105,0.001043,0.766691,0.025273,0.981100,0.498029,0.409173
3,54548.325,38.0,202500.0,2178.00,0.000000,480897.000,-258.000000,-18.0,0.0,-468.0,0.000000,14.000000,352.0,6.0,0.079341,0.047422,0.0,1,0,0.207480,0.167219,-13658,0.003257,0.091240,1,0.579531,0.000779,0.768826,0.025258,0.984100,0.267350,0.520898
4,NaN,40.0,247500.0,8595.00,0.000000,NaN,NaN,NaN,1.0,NaN,0.275429,10.575431,NaN,10.0,0.000000,0.019000,NaN,0,1,0.083300,0.041700,-16706,0.000000,0.008200,1,0.713225,0.000000,0.537600,0.001500,0.966200,0.577654,0.562207
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4375,21555.000,-1.0,202500.0,1253.50,0.111111,21555.000,-46.000000,-46.0,0.0,NaN,0.000000,4.000000,133.0,9.0,0.036400,0.006800,21555.0,1,0,0.041700,0.166700,-19823,0.000000,0.030900,1,0.640700,0.000000,0.830000,0.012200,0.987600,0.723753,0.355639
4376,NaN,-1.0,225000.0,0.00,0.000000,NaN,NaN,NaN,0.0,NaN,0.271494,7.901967,NaN,60.0,0.129900,0.160600,NaN,0,0,0.375000,0.333300,-13040,0.000000,0.222700,1,0.364555,-0.000518,0.802800,0.083300,0.985600,0.570632,0.515466
4377,45000.000,-1.0,270000.0,7650.00,0.500000,779242.500,-299.600000,-19.0,0.0,-166.0,0.000000,9.000000,1660.0,18.0,0.083589,0.046820,0.0,1,0,0.207235,0.167837,-13275,0.002724,0.093933,0,0.594696,0.000824,0.768625,0.024668,0.983420,0.327898,0.554947
4378,374400.000,NaN,270000.0,NaN,NaN,207733.500,-66.000000,-66.0,NaN,NaN,0.000000,13.971620,285.0,NaN,0.082591,0.047580,207733.5,0,0,0.205860,0.166648,-12050,0.002416,0.092972,0,0.601618,0.000630,0.767286,0.024594,0.981683,0.147856,0.540654
4379,75408.840,-1.0,216000.0,1125.00,0.333333,394398.000,-448.000000,-18.0,0.0,-574.0,0.000000,10.827036,353.0,18.8,0.079887,0.046280,0.0,0,0,0.206791,0.167487,-14940,0.002139,0.093484,0,0.441076,0.000583,0.766393,0.023842,0.981308,0.435468,0.324891

In [9]:
demo_data.columns

Index(['bureau_AMT_CREDIT_SUM_min', 'prev_SELLERPLACE_AREA_min',
       'AMT_INCOME_TOTAL', 'prev_AMT_DOWN_PAYMENT_mean',
       'prev_WEEKDAY_APPR_PROCESS_START_SATURDAY_count_norm',
       'bureau_AMT_CREDIT_SUM_DEBT_max', 'bureau_DAYS_CREDIT_UPDATE_mean',
       'bureau_DAYS_CREDIT_UPDATE_max',
       'prev_NAME_GOODS_CATEGORY_Furniture_count_norm',
       'bureau_DAYS_ENDDATE_FACT_max', 'AMT_REQ_CREDIT_BUREAU_QRT',
       'OWN_CAR_AGE', 'bureau_DAYS_CREDIT_ENDDATE_max',
       'prev_CNT_PAYMENT_mean', 'BASEMENTAREA_AVG', 'LANDAREA_AVG',
       'bureau_AMT_CREDIT_SUM_DEBT_min', 'FLAG_OWN_CAR',
       'ORGANIZATION_TYPE_Self-employed', 'FLOORSMIN_AVG', 'FLOORSMAX_AVG',
       'DAYS_BIRTH', 'NONLIVINGAREA_AVG', 'APARTMENTS_AVG',
       'HOUSETYPE_MODE_block of flats', 'EXT_SOURCE_2',
       'NONLIVINGAPARTMENTS_AVG', 'YEARS_BUILD_AVG', 'COMMONAREA_AVG',
       'YEARS_BEGINEXPLUATATION_AVG', 'EXT_SOURCE_1', 'EXT_SOURCE_3'],
      dtype='object')

## Интерпретация полей

### 'bureau_AMT_CREDIT_SUM_min',
Может быть NaN

Current credit amount for the Credit Bureau credit

Сумма открытого кредита, флоат, может быть 0

Описательная статистика, минимум по аппликанту.

### 'prev_SELLERPLACE_AREA_min',
Может быть NaN

Selling area of seller place of the previous application

Торговая площадь места продавца (вероятно, если аппликантом был продавец). -1 - считать что такой площади нет, в остальном - положительное значение, флоат, может быть 0.

Описательная статистика, минимум по аппликанту.

### 'AMT_INCOME_TOTAL', 
Income of the client

Флоат в сотнях тысяч валюты, 1 знак после запятой, положительное число.

### 'prev_AMT_DOWN_PAYMENT_mean',
Может быть NaN

Down payment on the previous application

Размер авансового платежа по предыдущему кредиту, положительный флоат, может быть 0.

Описательная статистика, максимум по аппликанту.

### 'prev_WEEKDAY_APPR_PROCESS_START_SATURDAY_count_norm',
Может быть NaN

On which day of the week did the client apply for previous application

Может быть NaN

Признак, приходил ли клиент на оформление кредита в субботу (шолом шаббат), положительный флоат, может быть 0
Описательная статистика, среднее значение случившихся фактов по аппликанту.

### 'bureau_AMT_CREDIT_SUM_DEBT_max', 
Может быть NaN

Current debt on Credit Bureau credit

Текущая сумма открытого кредита, может быть отрицательной (вероятно, возобновляемый кредит, переплата), может быть 0

Описательная статистика, максимум по аппликанту.


### 'bureau_DAYS_CREDIT_UPDATE_mean',
Может быть NaN

How many days before loan application did last information about the Credit Bureau credit come

Количество дней до подачи заявки, за которое происходило последнее обновление по кредитам аппликанта, может быть положительной (допришедшие данные после подачи заявки) может быть 0.

Описательная статистика, среднее по аппликанту.


### 'bureau_DAYS_CREDIT_UPDATE_max',
Может быть NaN

How many days before loan application did last information about the Credit Bureau credit come

Количество дней до подачи заявки, за которое происходило последнее обновление по кредитам аппликанта, может быть положительной (допришедшие данные после подачи заявки) может быть 0.

Описательная статистика, максимум по аппликанту.

### 'prev_NAME_GOODS_CATEGORY_Furniture_count_norm',
Может быть NaN

What kind of goods did the client apply for in the previous application

Признак, что клиент покупал именно мебель на прошлые кредиты, положительный флоат, может быть 0

Описательная статистика, среднее значение случившихся фактов по аппликанту.


### bureau_DAYS_ENDDATE_FACT_max',
Может быть NaN

Days since CB credit ended at the time of application in Home Credit (only for closed credit)

Количество дней, прошедших с момента закрытия предыдущего кредита, отрицательное число (принятый формат от текущей даты), флоат, может быть 0

Описательная статистика, максимум по аппликанту.

### 'AMT_REQ_CREDIT_BUREAU_QRT',
Number of enquiries to Credit Bureau about the client 3 month before application

Количество обращений клиента в кредитное бюро за квартал до месяца, предшествующего подаче заявки, положительный флоат, может быть 0

### 'OWN_CAR_AGE', 
Age of client's car

Флоат, от единиц до десятков, плавающая запятая в любой позиции (10.575431), положительное число, может быть 0

### 'bureau_DAYS_CREDIT_ENDDATE_max',
Может быть NaN

Remaining duration of CB credit (in days) at the time of application in Home Credit

Количество дней, прошедших с момента открытия предыдущего кредита, отрицательное число (принятый формат от текущей даты), флоат, может быть 0

Описательная статистика, максимум по аппликанту.

### 'prev_CNT_PAYMENT_mean',
Может быть NaN

Term of previous credit at application of the previous application

Срок предыдущего кредита, положительный флоат, может быть 0

Описательная статистика, среднее по аппликанту.

### 'BASEMENTAREA_AVG', 
Normalized information about building where the client lives, What is average (_AVG suffix)

Нормализованная средняя площадь подвала жилья аппликанта, положительный флоат, может быть 0

### 'LANDAREA_AVG',
Normalized information about building where the client lives, What is average (_AVG suffix)

Нормализованная средняя площадь прилегающей к дому территории жилья аппликанта, положительный флоат, может быть 0

### 'bureau_AMT_CREDIT_SUM_DEBT_min', 
Может быть NaN

Current debt on Credit Bureau credit

Текущая сумма открытого кредита, может быть отрицательной (вероятно, возобновляемый кредит, переплата), может быть 0

Описательная статистика, минимум по аппликанту.

### 'FLAG_OWN_CAR',
Flag if the client owns a car

Флаг, 1 или 0

### 'ORGANIZATION_TYPE_Self-employed', 
Type of organization where client works

Самозанятость, флаг, 1 или 0

### 'FLOORSMIN_AVG', 
Normalized information about building where the client lives, What is average (_AVG suffix)

Нормализованное среднее минимальное количество этажей жилья аппликанта, положительный флоат, может быть 0

### 'FLOORSMAX_AVG',
Normalized information about building where the client lives, What is average (_AVG suffix)

Нормализованное среднее максимальное количество этажей жилья аппликанта, положительный флоат, может быть 0

### 'DAYS_BIRTH',
Client's age in days at the time of application

Возраст клиента в днях, отрицательное число (принятый формат от текущей даты), флоат

### 'NONLIVINGAREA_AVG', 
Normalized information about building where the client lives, What is average (_AVG suffix)

Нормализованная средняя нежилая площадь жилья аппликанта

### 'APARTMENTS_AVG',
Normalized information about building where the client lives, What is average (_AVG suffix)

Нормализованная средняя площадь жилья аппликанта, положительный флоат, может быть 0

### 'HOUSETYPE_MODE_block of flats', 
Тип дома - многоквартирный, флаг, 1 или 0

### 'NONLIVINGAPARTMENTS_AVG', 
Normalized information about building where the client lives, What is average (_AVG suffix)

Нормализованная средняя нежилая площадь апартаментов (?) жилья аппликанта

### 'YEARS_BUILD_AVG', 
Normalized information about building where the client lives, What is average (_AVG suffix)

Нормализованный средний возраст жилья аппликанта, в годах, положительный флоат, может быть 0

### 'COMMONAREA_AVG',
Normalized information about building where the client lives, What is average (_AVG suffix)

Нормализованный средний возраст жилья аппликанта, в годах, положительный флоат, может быть 0

### 'YEARS_BEGINEXPLUATATION_AVG',
Normalized information about building where the client lives, What is average (_AVG suffix)

Нормализованный средний срок ввода в эксплуатацию жилья аппликанта, в годах, положительный флоат, может быть 0

### 'EXT_SOURCE_2', 'EXT_SOURCE_1', 'EXT_SOURCE_3'
Нормализованная кодированная переменная, скорее всего скоринг, положительный флоат

In [33]:
 data = {
        "userid": 1,
        "dataset": {
            "bureau_AMT_CREDIT_SUM_min": 2,
            "EXT_SOURCE_3": 1.0,
        },
    }

data

{'userid': 1, 'dataset': {'bureau_AMT_CREDIT_SUM_min': 2, 'EXT_SOURCE_3': 1.0}}

In [31]:
data['dataset'][EXT_SOURCE_3]

1.0

In [34]:
import pandas as pd
data_frame = pd.DataFrame(data['dataset'], index=[0])
object_columns = data_frame.loc[:,data_frame.dtypes==object].columns
data_frame[object_columns] = data_frame[object_columns].astype('float')
data_frame.dtypes

bureau_AMT_CREDIT_SUM_min      int64
EXT_SOURCE_3                 float64
dtype: object